# Generated by Django 3.0.5 on 2020-04-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
