# Generated by Django 3.0.5 on 2020-04-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_user_staff_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_encryption_key',
            field=models.CharField(default='', max_length=256),
        ),
    ]
