# Generated by Django 3.0.5 on 2020-04-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_status',
            field=models.BooleanField(default=False),
        ),
    ]
