# Generated by Django 3.0.5 on 2020-04-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_auto_20200410_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='posts',
            field=models.ManyToManyField(related_name='group', to='groups.Post'),
        ),
    ]
